[mgr]
prepend_keymap = [
  { on = "!",       run = "shell --orphan kitty", desc = "Ouvrir un terminal ici" },
  { on = "q",       run = "close",                desc = "Fermer l'onglet" },
  { on = "o",       run = "open",                 desc = "Ouvrir le(s) fichier(s)" },
  { on = "O",       run = "open --interactive",   desc = "Choisir l'ouvreur" },
  { on = "M",       run = "plugin mount",         desc = "Ouvrir le gestionnaire de montage" },
  { on = "+",       run  = "plugin zoom 1",       desc = "Zoom in" },
  { on = "-",       run  = "plugin zoom -1",      desc = "Zoom out" },
]
