### FILES TYPES ###

[filetype]
rules = [
	{ url = "**/.git/", fg = "#5853DC" },
	{ url = "**/.config/", fg = "#FFF700" },
	{ url = "**/Documents/", fg = "#71EACA" },
	{ url = "**/Downloads/", fg = "#7ED689" },
	{ url = "**/Github/", fg = "#5853DC" },
	{ url = "**/Images/", fg = "#FFC140" },
	{ url = "**/Obsidian/", fg = "#A640FF" },
	{ url = "**/hypr/", fg = "#40DAEE" },
	{ url = "**/hyprlock/", fg = "#40DAEE" },
	{ url = "**/kitty/", fg = "#B9720E" },
	{ url = "**/yazi/", fg = "#E8D600" },
	{ url = "**/rofi/", fg = "#B2B9A5" },
	{ url = "**/Electron/", fg = "#5E9CC3" },
	{ url = "**/nvim/", fg = "#159809" },
	{ url = "**/VSCode/", fg = "#2D70C2" },
	{ url = "**/VSCodium/", fg = "#2D70C2" },
	{ url = "**/Bitwarden/", fg = "#2D70C2" },
	{ url = "**/Discord/", fg = "#7388D9" },
	{ url = "**/Starship/", fg = "#DD0A78" },
	{ url = "**/docker-compose.yml", fg = "#1597ce" },
	{ url = "**/Dockerfile/", fg = "#1597ce" },
	{ url = "**/fontconfig/", fg = "#FFB700" },
	{ url = "**/Programmation/", fg = "#C54259" },
	{ url = "**/Trash/", fg = "#E0D8D6" },
	{ url = "**/MegaSync/", fg = "#BC0304" },

	{ url = "*/", fg = "#00AEFF" },

	{ url = "*.AppImage", fg = "#ffaf00" },
	{ url = "*.bin", fg = "#aaaaaa" },
	{ url = "*.conf", fg = "#FFF700" },
	{ url = "*.toml", fg = "#6d8086" },
	{ url = "*.css", fg = "#42a5f5" },
	{ url = "*.csv", fg = "#89e051" },
	{ url = "*.db", fg = "#f4a460" },
	{ url = "*.deb", fg = "#a80030" },
	{ url = "*.desktop", fg = "#48b9c7" },
	{ url = "*.html", fg = "#e34c26" },
	{ url = "*.img", fg = "#d0d0d0" },
	{ url = "*.iso", fg = "#ffcc66" },
	{ url = "*.jpeg", fg = "#c882e7" },
	{ url = "*.jpg", fg = "#c882e7" },
	{ url = "*.png", fg = "#c882e7" },
	{ url = "*.heic", fg = "#c882e7" },
	{ url = "*.json", fg = "#cbcb41" },
	{ url = "*.jsonc", fg = "#cbcb41" },
	{ url = "*.lua", fg = "#51a0cf" },
	{ url = "*.md", fg = "#00afff" },
	{ url = "*.txt", fg = "#00afff" },
	{ url = "*.mp3", fg = "#00FFFF" },
	{ url = "*.mp4", fg = "#FFE600" },
	{ url = "*.mov", fg = "#FFE600" },
	{ url = "*.pdf", fg = "#ff0000" },
	{ url = "*.rar", fg = "#ffaf00" },
	{ url = "*.tar", fg = "#ffaf00" },
	{ url = "*.gz", fg = "#ffaf00" },
	{ url = "*.zip", fg = "#ffaf00" },
	{ url = "*.sh", fg = "#4caf50" },
	{ url = "*.py", fg = "#3a6c95" },
]

### ICONS ###

[icon]
prepend_conds = [
	{ if = "dir", text = "", fg = "#00AEFF" },
]

dirs = [
	{ name = ".git", text = "", fg = "#5853DC" },
	{ name = ".config", text = "", fg = "#FFF700" },
	{ name = "Documents", text = "󰈙", fg = "#71EACA" },
	{ name = "Downloads", text = "󰇚", fg = "#7ED689" },
	{ name = "Github", text = "", fg = "#5853DC" },
	{ name = "Images", text = "", fg = "#FFC140" },
	{ name = "Obsidian", text = "", fg = "#A640FF" },
	{ name = "obsidian", text = "", fg = "#A640FF" },
	{ name = "hypr", text = "", fg = "#40DAEE" },
	{ name = "hyprlock", text = "", fg = "#40DAEE" },
	{ name = "kitty", text = "󰄛", fg = "#B9720E" },
	{ name = "yazi", text = "󰇥", fg = "#E8D600" },
	{ name = "rofi", text = "󰍜", fg = "#B2B9A5" },
	{ name = "Electron", text = "󱀤", fg = "#5E9CC3" },
	{ name = "electron", text = "󱀤", fg = "#5E9CC3" },
	{ name = "nvim", text = "", fg = "#159809" },
	{ name = "VSCode", text = "", fg = "#2D70C2" },
	{ name = "VSCodium", text = "", fg = "#2D70C2" },
	{ name = "Bitwarden", text = "", fg = "#2D70C2" },
	{ name = "Discord", text = "󰙯", fg = "#7388D9" },
	{ name = "discord", text = "󰙯", fg = "#7388D9" },
	{ name = "starship", text = "󰫢", fg = "#DD0A78" },
	{ name = "fontconfig", text = "", fg = "#FFB700" },
	{ name = "Programmation", text = "", fg = "#C54259" },
	{ name = "Trash", text = "", fg = "#E0D8D6" },
	{ name = "MegaSync", text = "", fg = "#BC0304" },
]

exts = [
	{ name = "AppImage", text = "", fg = "#ffaf00" },
	{ name = "bin", text = "", fg = "#aaaaaa" },
	{ name = "conf", text = "", fg = "#FFF700" },
	{ name = "css", text = "", fg = "#42a5f5" },
	{ name = "csv", text = "", fg = "#89e051" },
	{ name = "db", text = "", fg = "#f4a460" },
	{ name = "deb", text = "", fg = "#a80030" },
	{ name = "desktop", text = "", fg = "#48b9c7" },
	{ name = "html", text = "󰌝", fg = "#e34c26" },
	{ name = "img", text = "", fg = "#d0d0d0" },
	{ name = "iso", text = "󰗮", fg = "#ffcc66" },
	{ name = "jpeg", text = "󰋩", fg = "#c882e7" },
	{ name = "jpg", text = "󰋩", fg = "#c882e7" },
	{ name = "heic", text = "󰋩", fg = "#c882e7" },
	{ name = "json", text = "", fg = "#cbcb41" },
	{ name = "jsonc", text = "", fg = "#cbcb41" },
	{ name = "lua", text = "", fg = "#51a0cf" },
	{ name = "md", text = "", fg = "#00afff" },
	{ name = "mp3", text = "󰎇", fg = "#00FFFF" },
	{ name = "mp4", text = "", fg = "#FFE600" },
	{ name = "mov", text = "", fg = "#FFE600" },
	{ name = "pdf", text = "", fg = "#ff0000" },
	{ name = "png", text = "󰋩", fg = "#c882e7" },
	{ name = "rar", text = "", fg = "#ffaf00" },
	{ name = "sh", text = "", fg = "#4caf50" },
  { name = "py", text = "", fg = "#3a6c95" },
	{ name = "tar", text = "", fg = "#ffaf00" },
	{ name = "gz", text = "", fg = "#ffaf00" },
	{ name = "toml", text = "", fg = "#6d8086" },
	{ name = "txt", text = "󰦨", fg = "#00afff" },
	{ name = "zip", text = "", fg = "#ffaf00" },
	{ name = "trashinfo", text = "", fg = "#E0D8D6" },
]

### PLUGINS ###

[git]
unknown_sign = "?"
ignored_sign = ""
untracked_sign = "?"
unstaged_sign = "✎"
staged_sign = "+"
added_sign = "+"
deleted_sign = "x"
updated_sign = "✎"
clean_sign = ""
